# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bream/protocol_communication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bream/protocol_communication.proto',
  package='ont.bream.protocol_communication',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"bream/protocol_communication.proto\x12 ont.bream.protocol_communication\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x01\n\x13ProtocolDataResults\x12M\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32?.ont.bream.protocol_communication.ProtocolDataResults.DataEntry\x1a[\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12=\n\x05value\x18\x02 \x01(\x0b\x32..ont.bream.protocol_communication.ProtocolData:\x02\x38\x01\"\xaf\x07\n\x0cProtocolData\x12R\n\x13translocation_speed\x18\x01 \x01(\x0b\x32\x35.ont.bream.protocol_communication.ProtocolData.MinMax\x12\x46\n\x07q_score\x18\x02 \x01(\x0b\x32\x35.ont.bream.protocol_communication.ProtocolData.MinMax\x12J\n\x0btemperature\x18\x03 \x01(\x0b\x32\x35.ont.bream.protocol_communication.ProtocolData.MinMax\x12\x1b\n\x13\x62ias_voltage_offset\x18\x04 \x01(\x01\x12S\n\x05state\x18\x05 \x01(\x0e\x32\x44.ont.bream.protocol_communication.ProtocolData.ProtocolInternalState\x12J\n\x08mux_scan\x18\x06 \x01(\x0b\x32\x36.ont.bream.protocol_communication.ProtocolData.MuxScanH\x00\x12\x45\n\x05pause\x18\x07 \x01(\x0b\x32\x34.ont.bream.protocol_communication.ProtocolData.PauseH\x00\x12G\n\x06resume\x18\x08 \x01(\x0b\x32\x35.ont.bream.protocol_communication.ProtocolData.ResumeH\x00\x12\x43\n\x04stop\x18\n \x01(\x0b\x32\x33.ont.bream.protocol_communication.ProtocolData.StopH\x00\x12\x35\n\x11state_change_time\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\"\n\x06MinMax\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\x1a\t\n\x07MuxScan\x1a\x07\n\x05Pause\x1a\x08\n\x06Resume\x1a\x06\n\x04Stop\"\x88\x01\n\x15ProtocolInternalState\x12\x14\n\x10RUNNING_MUX_SCAN\x10\x00\x12\x16\n\x12RUNNING_SEQUENCING\x10\x01\x12\n\n\x06PAUSED\x10\x03\x12\x0b\n\x07PAUSING\x10\x05\x12\x0c\n\x08RESUMING\x10\x06\x12\x1a\n\x16PREPARING_FOR_MUX_SCAN\x10\x07\x42\x18\n\x16protocol_event_triggerb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_PROTOCOLDATA_PROTOCOLINTERNALSTATE = _descriptor.EnumDescriptor(
  name='ProtocolInternalState',
  full_name='ont.bream.protocol_communication.ProtocolData.ProtocolInternalState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RUNNING_MUX_SCAN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUNNING_SEQUENCING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PAUSED', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PAUSING', index=3, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESUMING', index=4, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PREPARING_FOR_MUX_SCAN', index=5, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1083,
  serialized_end=1219,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOLDATA_PROTOCOLINTERNALSTATE)


_PROTOCOLDATARESULTS_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='ont.bream.protocol_communication.ProtocolDataResults.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ont.bream.protocol_communication.ProtocolDataResults.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ont.bream.protocol_communication.ProtocolDataResults.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=299,
)

_PROTOCOLDATARESULTS = _descriptor.Descriptor(
  name='ProtocolDataResults',
  full_name='ont.bream.protocol_communication.ProtocolDataResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ont.bream.protocol_communication.ProtocolDataResults.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROTOCOLDATARESULTS_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=299,
)


_PROTOCOLDATA_MINMAX = _descriptor.Descriptor(
  name='MinMax',
  full_name='ont.bream.protocol_communication.ProtocolData.MinMax',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='ont.bream.protocol_communication.ProtocolData.MinMax.min', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max', full_name='ont.bream.protocol_communication.ProtocolData.MinMax.max', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1008,
  serialized_end=1042,
)

_PROTOCOLDATA_MUXSCAN = _descriptor.Descriptor(
  name='MuxScan',
  full_name='ont.bream.protocol_communication.ProtocolData.MuxScan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1044,
  serialized_end=1053,
)

_PROTOCOLDATA_PAUSE = _descriptor.Descriptor(
  name='Pause',
  full_name='ont.bream.protocol_communication.ProtocolData.Pause',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1055,
  serialized_end=1062,
)

_PROTOCOLDATA_RESUME = _descriptor.Descriptor(
  name='Resume',
  full_name='ont.bream.protocol_communication.ProtocolData.Resume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1064,
  serialized_end=1072,
)

_PROTOCOLDATA_STOP = _descriptor.Descriptor(
  name='Stop',
  full_name='ont.bream.protocol_communication.ProtocolData.Stop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1074,
  serialized_end=1080,
)

_PROTOCOLDATA = _descriptor.Descriptor(
  name='ProtocolData',
  full_name='ont.bream.protocol_communication.ProtocolData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='translocation_speed', full_name='ont.bream.protocol_communication.ProtocolData.translocation_speed', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_score', full_name='ont.bream.protocol_communication.ProtocolData.q_score', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='ont.bream.protocol_communication.ProtocolData.temperature', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bias_voltage_offset', full_name='ont.bream.protocol_communication.ProtocolData.bias_voltage_offset', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='ont.bream.protocol_communication.ProtocolData.state', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mux_scan', full_name='ont.bream.protocol_communication.ProtocolData.mux_scan', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pause', full_name='ont.bream.protocol_communication.ProtocolData.pause', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resume', full_name='ont.bream.protocol_communication.ProtocolData.resume', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop', full_name='ont.bream.protocol_communication.ProtocolData.stop', index=8,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state_change_time', full_name='ont.bream.protocol_communication.ProtocolData.state_change_time', index=9,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROTOCOLDATA_MINMAX, _PROTOCOLDATA_MUXSCAN, _PROTOCOLDATA_PAUSE, _PROTOCOLDATA_RESUME, _PROTOCOLDATA_STOP, ],
  enum_types=[
    _PROTOCOLDATA_PROTOCOLINTERNALSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='protocol_event_trigger', full_name='ont.bream.protocol_communication.ProtocolData.protocol_event_trigger',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=302,
  serialized_end=1245,
)

_PROTOCOLDATARESULTS_DATAENTRY.fields_by_name['value'].message_type = _PROTOCOLDATA
_PROTOCOLDATARESULTS_DATAENTRY.containing_type = _PROTOCOLDATARESULTS
_PROTOCOLDATARESULTS.fields_by_name['data'].message_type = _PROTOCOLDATARESULTS_DATAENTRY
_PROTOCOLDATA_MINMAX.containing_type = _PROTOCOLDATA
_PROTOCOLDATA_MUXSCAN.containing_type = _PROTOCOLDATA
_PROTOCOLDATA_PAUSE.containing_type = _PROTOCOLDATA
_PROTOCOLDATA_RESUME.containing_type = _PROTOCOLDATA
_PROTOCOLDATA_STOP.containing_type = _PROTOCOLDATA
_PROTOCOLDATA.fields_by_name['translocation_speed'].message_type = _PROTOCOLDATA_MINMAX
_PROTOCOLDATA.fields_by_name['q_score'].message_type = _PROTOCOLDATA_MINMAX
_PROTOCOLDATA.fields_by_name['temperature'].message_type = _PROTOCOLDATA_MINMAX
_PROTOCOLDATA.fields_by_name['state'].enum_type = _PROTOCOLDATA_PROTOCOLINTERNALSTATE
_PROTOCOLDATA.fields_by_name['mux_scan'].message_type = _PROTOCOLDATA_MUXSCAN
_PROTOCOLDATA.fields_by_name['pause'].message_type = _PROTOCOLDATA_PAUSE
_PROTOCOLDATA.fields_by_name['resume'].message_type = _PROTOCOLDATA_RESUME
_PROTOCOLDATA.fields_by_name['stop'].message_type = _PROTOCOLDATA_STOP
_PROTOCOLDATA.fields_by_name['state_change_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PROTOCOLDATA_PROTOCOLINTERNALSTATE.containing_type = _PROTOCOLDATA
_PROTOCOLDATA.oneofs_by_name['protocol_event_trigger'].fields.append(
  _PROTOCOLDATA.fields_by_name['mux_scan'])
_PROTOCOLDATA.fields_by_name['mux_scan'].containing_oneof = _PROTOCOLDATA.oneofs_by_name['protocol_event_trigger']
_PROTOCOLDATA.oneofs_by_name['protocol_event_trigger'].fields.append(
  _PROTOCOLDATA.fields_by_name['pause'])
_PROTOCOLDATA.fields_by_name['pause'].containing_oneof = _PROTOCOLDATA.oneofs_by_name['protocol_event_trigger']
_PROTOCOLDATA.oneofs_by_name['protocol_event_trigger'].fields.append(
  _PROTOCOLDATA.fields_by_name['resume'])
_PROTOCOLDATA.fields_by_name['resume'].containing_oneof = _PROTOCOLDATA.oneofs_by_name['protocol_event_trigger']
_PROTOCOLDATA.oneofs_by_name['protocol_event_trigger'].fields.append(
  _PROTOCOLDATA.fields_by_name['stop'])
_PROTOCOLDATA.fields_by_name['stop'].containing_oneof = _PROTOCOLDATA.oneofs_by_name['protocol_event_trigger']
DESCRIPTOR.message_types_by_name['ProtocolDataResults'] = _PROTOCOLDATARESULTS
DESCRIPTOR.message_types_by_name['ProtocolData'] = _PROTOCOLDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtocolDataResults = _reflection.GeneratedProtocolMessageType('ProtocolDataResults', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _PROTOCOLDATARESULTS_DATAENTRY,
    '__module__' : 'bream.protocol_communication_pb2'
    # @@protoc_insertion_point(class_scope:ont.bream.protocol_communication.ProtocolDataResults.DataEntry)
    })
  ,
  'DESCRIPTOR' : _PROTOCOLDATARESULTS,
  '__module__' : 'bream.protocol_communication_pb2'
  # @@protoc_insertion_point(class_scope:ont.bream.protocol_communication.ProtocolDataResults)
  })
_sym_db.RegisterMessage(ProtocolDataResults)
_sym_db.RegisterMessage(ProtocolDataResults.DataEntry)

ProtocolData = _reflection.GeneratedProtocolMessageType('ProtocolData', (_message.Message,), {

  'MinMax' : _reflection.GeneratedProtocolMessageType('MinMax', (_message.Message,), {
    'DESCRIPTOR' : _PROTOCOLDATA_MINMAX,
    '__module__' : 'bream.protocol_communication_pb2'
    # @@protoc_insertion_point(class_scope:ont.bream.protocol_communication.ProtocolData.MinMax)
    })
  ,

  'MuxScan' : _reflection.GeneratedProtocolMessageType('MuxScan', (_message.Message,), {
    'DESCRIPTOR' : _PROTOCOLDATA_MUXSCAN,
    '__module__' : 'bream.protocol_communication_pb2'
    # @@protoc_insertion_point(class_scope:ont.bream.protocol_communication.ProtocolData.MuxScan)
    })
  ,

  'Pause' : _reflection.GeneratedProtocolMessageType('Pause', (_message.Message,), {
    'DESCRIPTOR' : _PROTOCOLDATA_PAUSE,
    '__module__' : 'bream.protocol_communication_pb2'
    # @@protoc_insertion_point(class_scope:ont.bream.protocol_communication.ProtocolData.Pause)
    })
  ,

  'Resume' : _reflection.GeneratedProtocolMessageType('Resume', (_message.Message,), {
    'DESCRIPTOR' : _PROTOCOLDATA_RESUME,
    '__module__' : 'bream.protocol_communication_pb2'
    # @@protoc_insertion_point(class_scope:ont.bream.protocol_communication.ProtocolData.Resume)
    })
  ,

  'Stop' : _reflection.GeneratedProtocolMessageType('Stop', (_message.Message,), {
    'DESCRIPTOR' : _PROTOCOLDATA_STOP,
    '__module__' : 'bream.protocol_communication_pb2'
    # @@protoc_insertion_point(class_scope:ont.bream.protocol_communication.ProtocolData.Stop)
    })
  ,
  'DESCRIPTOR' : _PROTOCOLDATA,
  '__module__' : 'bream.protocol_communication_pb2'
  # @@protoc_insertion_point(class_scope:ont.bream.protocol_communication.ProtocolData)
  })
_sym_db.RegisterMessage(ProtocolData)
_sym_db.RegisterMessage(ProtocolData.MinMax)
_sym_db.RegisterMessage(ProtocolData.MuxScan)
_sym_db.RegisterMessage(ProtocolData.Pause)
_sym_db.RegisterMessage(ProtocolData.Resume)
_sym_db.RegisterMessage(ProtocolData.Stop)


_PROTOCOLDATARESULTS_DATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
