# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol_ui.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol_ui.proto',
  package='bream.gui',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11protocol_ui.proto\x12\tbream.gui\x1a\x19google/protobuf/any.proto\"C\n\x0eUIProgressMeta\x12\x0f\n\x07minimum\x18\x01 \x01(\x05\x12\x0f\n\x07maximum\x18\x02 \x01(\x05\x12\x0f\n\x07\x63urrent\x18\x03 \x01(\x05\"\x84\x01\n\rUICommandMeta\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x34\n\x06params\x18\x02 \x03(\x0b\x32$.bream.gui.UICommandMeta.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\x10UICoordinateMeta\x12\x0c\n\x04step\x18\x01 \x01(\x05\"\xd3\x05\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\x05\x12+\n\x07request\x18\x02 \x01(\x0b\x32\x1a.bream.gui.Message.Request\x12\x32\n\x08response\x18\x03 \x03(\x0b\x32 .bream.gui.Message.ResponseEntry\x12\r\n\x05\x61sync\x18\x04 \x01(\x08\x12\x16\n\x0eresponse_error\x18\x05 \x01(\t\x1a\x82\x04\n\x07Request\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x0b\x63\x61ncellable\x18\x03 \x01(\x08\x12\x30\n\x06values\x18\x04 \x03(\x0b\x32 .bream.gui.Message.Request.Value\x1a\x8b\x03\n\x05Value\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nidentifier\x18\x03 \x01(\t\x12\x1a\n\x12set_default_values\x18\x04 \x03(\t\x12\x12\n\nregex_test\x18\x05 \x01(\t\x12\x15\n\rerror_message\x18\x06 \x01(\t\x12\x33\n\x04type\x18\x07 \x01(\x0e\x32%.bream.gui.Message.Request.Value.Type\x12\"\n\x04meta\x18\x08 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x15\n\rset_one_value\x18\n \x03(\t\x12\x1a\n\x12set_multiple_value\x18\x0b \x03(\t\"w\n\x04Type\x12\n\n\x06STRING\x10\x00\x12\x0b\n\x07SET_ONE\x10\x01\x12\x10\n\x0cSET_MULTIPLE\x10\x02\x12\r\n\tSHOW_TEXT\x10\x03\x12\x0c\n\x08PROGRESS\x10\x04\x12\n\n\x06\x42UTTON\x10\x05\x12\x0b\n\x07\x43OMMAND\x10\x06\x12\x0e\n\nCOORDINATE\x10\x07\x1a/\n\rResponseEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])



_MESSAGE_REQUEST_VALUE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='bream.gui.Message.Request.Value.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STRING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_ONE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_MULTIPLE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHOW_TEXT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROGRESS', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUTTON', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMAND', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COORDINATE', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=853,
  serialized_end=972,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_REQUEST_VALUE_TYPE)


_UIPROGRESSMETA = _descriptor.Descriptor(
  name='UIProgressMeta',
  full_name='bream.gui.UIProgressMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='minimum', full_name='bream.gui.UIProgressMeta.minimum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maximum', full_name='bream.gui.UIProgressMeta.maximum', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current', full_name='bream.gui.UIProgressMeta.current', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=126,
)


_UICOMMANDMETA_PARAMSENTRY = _descriptor.Descriptor(
  name='ParamsEntry',
  full_name='bream.gui.UICommandMeta.ParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='bream.gui.UICommandMeta.ParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='bream.gui.UICommandMeta.ParamsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=261,
)

_UICOMMANDMETA = _descriptor.Descriptor(
  name='UICommandMeta',
  full_name='bream.gui.UICommandMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='bream.gui.UICommandMeta.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='bream.gui.UICommandMeta.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_UICOMMANDMETA_PARAMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=261,
)


_UICOORDINATEMETA = _descriptor.Descriptor(
  name='UICoordinateMeta',
  full_name='bream.gui.UICoordinateMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='step', full_name='bream.gui.UICoordinateMeta.step', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=295,
)


_MESSAGE_REQUEST_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='bream.gui.Message.Request.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='bream.gui.Message.Request.Value.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='bream.gui.Message.Request.Value.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='bream.gui.Message.Request.Value.identifier', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_default_values', full_name='bream.gui.Message.Request.Value.set_default_values', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regex_test', full_name='bream.gui.Message.Request.Value.regex_test', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='bream.gui.Message.Request.Value.error_message', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='bream.gui.Message.Request.Value.type', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta', full_name='bream.gui.Message.Request.Value.meta', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_one_value', full_name='bream.gui.Message.Request.Value.set_one_value', index=8,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_multiple_value', full_name='bream.gui.Message.Request.Value.set_multiple_value', index=9,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGE_REQUEST_VALUE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=972,
)

_MESSAGE_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='bream.gui.Message.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='bream.gui.Message.Request.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='bream.gui.Message.Request.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cancellable', full_name='bream.gui.Message.Request.cancellable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='bream.gui.Message.Request.values', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_REQUEST_VALUE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=972,
)

_MESSAGE_RESPONSEENTRY = _descriptor.Descriptor(
  name='ResponseEntry',
  full_name='bream.gui.Message.ResponseEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='bream.gui.Message.ResponseEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='bream.gui.Message.ResponseEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=974,
  serialized_end=1021,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='bream.gui.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bream.gui.Message.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='bream.gui.Message.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='bream.gui.Message.response', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='async', full_name='bream.gui.Message.async', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_error', full_name='bream.gui.Message.response_error', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_REQUEST, _MESSAGE_RESPONSEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=1021,
)

_UICOMMANDMETA_PARAMSENTRY.containing_type = _UICOMMANDMETA
_UICOMMANDMETA.fields_by_name['params'].message_type = _UICOMMANDMETA_PARAMSENTRY
_MESSAGE_REQUEST_VALUE.fields_by_name['type'].enum_type = _MESSAGE_REQUEST_VALUE_TYPE
_MESSAGE_REQUEST_VALUE.fields_by_name['meta'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_MESSAGE_REQUEST_VALUE.containing_type = _MESSAGE_REQUEST
_MESSAGE_REQUEST_VALUE_TYPE.containing_type = _MESSAGE_REQUEST_VALUE
_MESSAGE_REQUEST.fields_by_name['values'].message_type = _MESSAGE_REQUEST_VALUE
_MESSAGE_REQUEST.containing_type = _MESSAGE
_MESSAGE_RESPONSEENTRY.containing_type = _MESSAGE
_MESSAGE.fields_by_name['request'].message_type = _MESSAGE_REQUEST
_MESSAGE.fields_by_name['response'].message_type = _MESSAGE_RESPONSEENTRY
DESCRIPTOR.message_types_by_name['UIProgressMeta'] = _UIPROGRESSMETA
DESCRIPTOR.message_types_by_name['UICommandMeta'] = _UICOMMANDMETA
DESCRIPTOR.message_types_by_name['UICoordinateMeta'] = _UICOORDINATEMETA
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UIProgressMeta = _reflection.GeneratedProtocolMessageType('UIProgressMeta', (_message.Message,), {
  'DESCRIPTOR' : _UIPROGRESSMETA,
  '__module__' : 'protocol_ui_pb2'
  # @@protoc_insertion_point(class_scope:bream.gui.UIProgressMeta)
  })
_sym_db.RegisterMessage(UIProgressMeta)

UICommandMeta = _reflection.GeneratedProtocolMessageType('UICommandMeta', (_message.Message,), {

  'ParamsEntry' : _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _UICOMMANDMETA_PARAMSENTRY,
    '__module__' : 'protocol_ui_pb2'
    # @@protoc_insertion_point(class_scope:bream.gui.UICommandMeta.ParamsEntry)
    })
  ,
  'DESCRIPTOR' : _UICOMMANDMETA,
  '__module__' : 'protocol_ui_pb2'
  # @@protoc_insertion_point(class_scope:bream.gui.UICommandMeta)
  })
_sym_db.RegisterMessage(UICommandMeta)
_sym_db.RegisterMessage(UICommandMeta.ParamsEntry)

UICoordinateMeta = _reflection.GeneratedProtocolMessageType('UICoordinateMeta', (_message.Message,), {
  'DESCRIPTOR' : _UICOORDINATEMETA,
  '__module__' : 'protocol_ui_pb2'
  # @@protoc_insertion_point(class_scope:bream.gui.UICoordinateMeta)
  })
_sym_db.RegisterMessage(UICoordinateMeta)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {

  'Request' : _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {

    'Value' : _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
      'DESCRIPTOR' : _MESSAGE_REQUEST_VALUE,
      '__module__' : 'protocol_ui_pb2'
      # @@protoc_insertion_point(class_scope:bream.gui.Message.Request.Value)
      })
    ,
    'DESCRIPTOR' : _MESSAGE_REQUEST,
    '__module__' : 'protocol_ui_pb2'
    # @@protoc_insertion_point(class_scope:bream.gui.Message.Request)
    })
  ,

  'ResponseEntry' : _reflection.GeneratedProtocolMessageType('ResponseEntry', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGE_RESPONSEENTRY,
    '__module__' : 'protocol_ui_pb2'
    # @@protoc_insertion_point(class_scope:bream.gui.Message.ResponseEntry)
    })
  ,
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'protocol_ui_pb2'
  # @@protoc_insertion_point(class_scope:bream.gui.Message)
  })
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.Request)
_sym_db.RegisterMessage(Message.Request.Value)
_sym_db.RegisterMessage(Message.ResponseEntry)


_UICOMMANDMETA_PARAMSENTRY._options = None
_MESSAGE_RESPONSEENTRY._options = None
# @@protoc_insertion_point(module_scope)
